name: Flex
markdown: redcarpet
highlighter: pygments

#############################
# Mateusz Szynka home theme #
#############################

#################
# Site settings
#################
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mszynka.pl"
permalink: /blog/:year/:month/:title/

#################
# HEAD
#################
title: Mateusz Szynka
subtitle: web developer and programmer
author: "Mateusz Szynka"
lang: "en"
favicon: "/img/favicon.ico"
description: >
  I'm a beginner web developer and programmer. Currently studying Computer Science at Poznan University of Technology and working as Full Stack .NET Developer at Mediporta.pl. Thousand ideas but not enough time for all of them.

#################
# Contact settings
#################
email: devmsw12@gmail.com
github_username:  mszynka
linkedin_username: maszynka

#################
# Projects
#################
collections:
  projects:
    output: true

exclude: [
	"fontawesome/package.json",
]
