#############################
# Mateusz Szynka home theme #
#############################

#################
# Site settings
#################
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mszynka.pl"
permalink: /blog/:year/:month/:title/

#################
# HEAD
#################
title: Mateusz Szynka
subtitle: web developer and designer
author: "Mateusz Szynka"
lang: "en"
favicon: "/img/favicon.ico"
description: >
  I'm a beginner web developer and designer. Currently studying Computer Science at Poznan University of Technology and working as Front End Developer at Caliper.pl. Thousand ideas but not enough time for all of them.

#################
# Contact settings
#################
email: devmsw12@gmail.com
twitter_username: mszynka_
github_username:  mszynka

#################
# Build settings
#################
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude: [
	"bootstrap/fonts/",
	"bootstrap/grunt/",
	"bootstrap/js/",
	"bootstrap/less/",
	"bootstrap/node_modules/",
	"bootstrap/CNAME",
	"bootstrap/Gruntfile.js",
	"bootstrap/LICENSE",
	"bootstrap/README.md",
	"bootstrap/package.json",
	"fontawesome/package.json"
]