# Site settings
title: Mateusz Szynka
description: >- # this means to ignore newlines until "baseurl:"
  web developer and programmer
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: mszynka/mszynka.github.io

plugins:
  - jekyll-remote-theme

remote_theme: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Mateusz Szynka
  image    : img/face
  email    : devmsw12@gmail.com
  github   : mszynka
  linkedin : maszynka


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock